
theme = "bogster"
[editor]
mouse = true
auto-save = true
line-number = "relative"
bufferline = "always"




[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"


[editor.soft-wrap]
enable = true
# wrap-at-text-width = true



[editor.whitespace.render]
space = "all"
tab = "all"
newline = "none"

[editor.statusline]
left = [ "mode", "spinner", "diagnostics" ]
center = [ "file-name", "separator", "version-control", "separator" ]
right = [ "position", "position-percentage", "total-line-numbers" ]
separator = ""
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.lsp]
display-inlay-hints = true
auto-signature-help = false
display-messages = true


[editor.file-picker]
hidden = false


[keys.normal]
ins = "insert_mode"
esc = ["collapse_selection", "keep_primary_selection"]
C-o = ":open ~/.config/helix/config.toml" # Maps Ctrl-o to opening of the helix config file
C-r = ":config-reload"
S-tab = ":buffer-previous"
A-w = ":buffer-close"
"S-down" =  "page_cursor_half_down"
S-up = "page_cursor_half_up"
space.c = "toggle_comments"
g = { a = "code_action" } # ga to open code actions
X = "extend_line_above" # Shift+x to select the whole line above
"D" = ["extend_to_line_bounds", "delete_selection"]
# c = ["trim_selections", "change_selection"] # Make 'c' automatically strip the selection of extra whitespace
a = ["append_mode", "collapse_selection"] # Remove the selection when entering insert mode with 'a'
p = "paste_clipboard_before"
y = "yank_main_selection_to_clipboard"
C-right = "move_next_word_start"
C-left = "move_prev_word_end"
"K" = "hover"
space.x = ":toggle whitespace.render all none"
S-space = ["half_page_up"]
space."." = "file_picker_in_current_buffer_directory"

# [keys.normal.space]
"C-down" = ["extend_to_line_bounds", "delete_selection", "paste_after"]
"C-up" = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]

[keys.insert]

ins = "normal_mode"


C-right = "move_next_word_start"
C-left = "move_prev_word_end"
