# ─────────────────────────────────────────────────────────────────────────────
# Theme and General Editor Settings
# ─────────────────────────────────────────────────────────────────────────────
theme = "ayu_dark"                  # Sets the Helix color theme to "ayu_dark"

[editor]
mouse = true                        # Enable mouse support
auto-save = true                   # Automatically save files
line-number = "relative"           # Use relative line numbers
bufferline = "always"              # Always show open buffers in the status line
end-of-line-diagnostics = "hint"   # Show inline diagnostics info for hints

[editor.cursor-shape]
insert = "bar"     # Shape of cursor in Insert mode
normal = "block"   # Shape of cursor in Normal mode
select = "underline"  # Shape of cursor in Select mode

[editor.soft-wrap]
enable = true                      # Soft wrap long lines
# wrap-at-text-width = true        # (Optional) Wrap lines at configured text width

[editor.whitespace.render]
space = "all"      # Render all spaces
tab = "all"        # Render tabs
newline = "none"   # Don't render the newline symbol

# ─────────────────────────────────────────────────────────────────────────────
# Status Line Configuration
# ─────────────────────────────────────────────────────────────────────────────
[editor.statusline]
left = [ "mode", "spinner", "diagnostics" ]
center = [ "file-name", "separator", "version-control", "separator" ]
right = [ "position", "position-percentage", "total-line-numbers" ]
separator = ""

# Labels for modes in the status line
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

# ─────────────────────────────────────────────────────────────────────────────
# Language Server Protocol (LSP) Settings
# ─────────────────────────────────────────────────────────────────────────────
[editor.lsp]
display-inlay-hints = true   # Show inline hints (e.g., parameter hints)
auto-signature-help = false  # Disable auto signature help pop-up
display-messages = true      # Show LSP messages in the editor

# ─────────────────────────────────────────────────────────────────────────────
# File Picker
# ─────────────────────────────────────────────────────────────────────────────
[editor.file-picker]
hidden = false               # Show hidden files in file picker

# ─────────────────────────────────────────────────────────────────────────────
# Keybindings in Normal Mode
# ─────────────────────────────────────────────────────────────────────────────
[keys.normal]
# Basic mode switching
ins = "insert_mode"                                      # Switch to Insert mode
esc = ["collapse_selection", "keep_primary_selection"]    # ESC collapses selections, but keeps primary selection

# Config-related commands
C-o = ":open ~/.config/helix/config.toml"  # Ctrl + o opens this config file
C-r = ":config-reload"                     # Ctrl + r reloads config

# Buffer navigation
S-tab = ":buffer-previous"                 # Shift + Tab to go to previous buffer
A-w = ":buffer-close"                      # Alt + w to close current buffer

# Page scrolling
"S-down" = "page_cursor_half_down"         # Shift + Down arrow → half-page scroll
S-up = "page_cursor_half_up"               # Shift + Up arrow → half-page scroll
S-space = ["half_page_up"]                 # Shift + Space → half-page scroll up

# Comments and code actions
space.c = "toggle_comments"                # Space + c → toggle comments
g = { a = "code_action" }                  # g then a → open code actions

# Selecting, deleting, and moving lines
X = "extend_line_above"                    # Shift + x → select the whole line above
"D" = ["extend_to_line_bounds", "delete_selection"]  
       # Shift + d → select the whole line bounds & delete selection

# Insert/append
a = ["append_mode", "collapse_selection"]  # 'a' → enter insert mode (append), collapse selection

# Copy/Paste
p = "paste_clipboard_before"               # Paste from clipboard before cursor
y = "yank_main_selection_to_clipboard"     # Yank selection to system clipboard

# Word navigation
C-right = "move_next_word_start"           # Ctrl + → → move to start of next word
C-left = "move_prev_word_end"              # Ctrl + ← → move to end of previous word

# Hover info / LSP
"K" = "hover"                              # Shift + K → show hover information

# Whitespace rendering
space.x = ":toggle whitespace.render all none"  
          # Space + x → toggle whitespace rendering on/off

# File picker in current dir
space."." = "file_picker_in_current_buffer_directory"  
            # Space + . → open file picker in current buffer's directory

# Move lines up/down with paste
"C-down" = ["extend_to_line_bounds", "delete_selection", "paste_after"]
"C-up"   = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]

# ─────────────────────────────────────────────────────────────────────────────
# Keybindings in Insert Mode
# ─────────────────────────────────────────────────────────────────────────────
[keys.insert]
ins = "normal_mode"          # 'Ins' key → go back to Normal mode
C-left = "move_prev_word_end"   
C-right = "move_next_word_start"

# End of config
